# Generated by Django 5.0.11 on 2026-01-16 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contrato', 'Contrato'), ('demanda', 'Demanda'), ('poder', 'Poder'), ('sentencia', 'Sentencia'), ('escritura', 'Escritura'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de documento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='legal_documents/', verbose_name='Archivo')),
                ('file_size', models.IntegerField(editable=False, verbose_name='Tamaño del archivo (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Confidencial')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='Caso')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
