# Generated by Django 5.0.11 on 2026-01-19 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_add_performance_indexes'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case'], name='doc_case_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='doc_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='doc_type_idx'),
        ),
    ]
