# Generated by Django 5.0.11 on 2026-06-06 17:31

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.get_document_upload_path, verbose_name='Archivo'),
        ),
    ]
