# Generated by Django 5.0.11 on 2026-01-16 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de caso')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('penal', 'Penal'), ('laboral', 'Laboral'), ('mercantil', 'Mercantil'), ('familia', 'Familia')], max_length=20, verbose_name='Tipo de caso')),
                ('status', models.CharField(choices=[('en_proceso', 'En Proceso'), ('pendiente_documentos', 'Pendiente Documentos'), ('en_revision', 'En Revisión'), ('cerrado', 'Cerrado')], default='en_proceso', max_length=30, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridad')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-created_at'],
            },
        ),
    ]
