/**
 * README generator for screenshot documentation.
 *
 * Generates a markdown README file that indexes all captured screenshots
 * with descriptions, organized by module.
 */

import * as fs from 'fs';
import * as path from 'path';
import { SCREENSHOT_BASE_DIR, getCapturedScreenshots, ScreenshotInfo } from './screenshot-utils';
import { MODULES, ModuleConfig } from './module-config';

/**
 * Generate the complete README markdown content
 */
export function generateReadmeContent(): string {
  const timestamp = new Date().toISOString();
  const screenshots = getCapturedScreenshots();

  let content = `# LegalDocs Manager - Visual Documentation

> Auto-generated documentation with screenshots of all application interfaces.

**Generated**: ${timestamp}

## Table of Contents

`;

  // Generate table of contents
  for (const module of MODULES) {
    const moduleScreenshots = screenshots.get(module.id);
    if (moduleScreenshots && moduleScreenshots.length > 0) {
      const anchor = module.name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      content += `- [${module.name}](#${anchor})\n`;
    }
  }

  content += `\n---\n\n`;

  // Generate content for each module
  for (const module of MODULES) {
    const moduleScreenshots = screenshots.get(module.id);
    if (moduleScreenshots && moduleScreenshots.length > 0) {
      content += generateModuleSection(module, moduleScreenshots);
    }
  }

  // Add footer
  content += `---

## About This Documentation

This visual documentation was automatically generated using [Playwright](https://playwright.dev/)
to capture screenshots of the LegalDocs Manager application.

### Regenerating Screenshots

\`\`\`bash
cd tests/e2e
DISABLE_THROTTLING=1 npx playwright test docs/generate-screenshots.spec.ts
\`\`\`

### Requirements

- Django server running at \`http://localhost:8000\`
- Admin user with known credentials
- \`DISABLE_THROTTLING=1\` environment variable set

---

*Generated by LegalDocs Manager Screenshot Documentation System*
`;

  return content;
}

/**
 * Generate markdown section for a single module
 */
function generateModuleSection(module: ModuleConfig, screenshots: ScreenshotInfo[]): string {
  let section = `## ${module.name}

${module.description}

`;

  for (const screenshot of screenshots) {
    // Format the screenshot name for display
    const displayName = formatScreenshotName(screenshot.filename);

    section += `### ${displayName}

${screenshot.description}

![${displayName}](./${screenshot.path})

`;
  }

  section += `---\n\n`;

  return section;
}

/**
 * Format screenshot filename into human-readable title
 */
function formatScreenshotName(filename: string): string {
  // Remove order prefix and extension: "01-login-page.png" -> "Login Page"
  return filename
    .replace(/^\d+-/, '')           // Remove leading numbers and dash
    .replace(/\.png$/, '')          // Remove extension
    .split('-')                     // Split on dashes
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))  // Capitalize
    .join(' ');                     // Join with spaces
}

/**
 * Write the README file to the screenshots directory
 */
export async function writeReadme(): Promise<string> {
  const content = generateReadmeContent();
  const readmePath = path.join(SCREENSHOT_BASE_DIR, 'README.md');

  fs.writeFileSync(readmePath, content, 'utf-8');
  console.log(`\n📝 Generated README: ${readmePath}`);

  return readmePath;
}

/**
 * Validate that all expected screenshots are present
 */
export function validateScreenshots(): { valid: boolean; missing: string[]; extra: string[] } {
  const screenshots = getCapturedScreenshots();
  const missing: string[] = [];
  const extra: string[] = [];

  for (const module of MODULES) {
    const moduleScreenshots = screenshots.get(module.id) || [];
    const actualCount = moduleScreenshots.length;
    const expectedCount = module.expectedScreenshots;

    if (actualCount < expectedCount) {
      missing.push(`${module.id}: expected ${expectedCount}, got ${actualCount}`);
    } else if (actualCount > expectedCount) {
      extra.push(`${module.id}: expected ${expectedCount}, got ${actualCount}`);
    }
  }

  return {
    valid: missing.length === 0,
    missing,
    extra,
  };
}

/**
 * Get summary statistics
 */
export function getSummary(): {
  totalModules: number;
  totalScreenshots: number;
  moduleBreakdown: Array<{ module: string; count: number }>;
} {
  const screenshots = getCapturedScreenshots();
  let total = 0;
  const breakdown: Array<{ module: string; count: number }> = [];

  for (const module of MODULES) {
    const moduleScreenshots = screenshots.get(module.id) || [];
    const count = moduleScreenshots.length;
    total += count;
    if (count > 0) {
      breakdown.push({ module: module.name, count });
    }
  }

  return {
    totalModules: breakdown.length,
    totalScreenshots: total,
    moduleBreakdown: breakdown,
  };
}
